In [1]:
val textFile = spark.read.textFile("README.md")

Intitializing Scala interpreter ...

Spark Web UI available at http://DESKTOP-7M17AKF:4041
SparkContext available as 'sc' (version = 2.4.5, master = local[*], app id = local-1589192773996)
SparkSession available as 'spark'


textFile: org.apache.spark.sql.Dataset[String] = [value: string]


In [4]:
textFile.collect()

res2: Array[String] = Array(# scalaSpark)


In [14]:
textFile

res12: org.apache.spark.sql.Dataset[String] = [value: string]


In [4]:
val sourceFile = "C:/workspace/workplace/scala/SparkScala/fakefriends.csv"

sourceFile: String = C:/workspace/workplace/scala/SparkScala/fakefriends.csv


In [5]:
val lines = sc.textFile(sourceFile)

lines: org.apache.spark.rdd.RDD[String] = C:/workspace/workplace/scala/SparkScala/fakefriends.csv MapPartitionsRDD[1] at textFile at <console>:27


In [6]:
lines.take(1)

res0: Array[String] = Array(0,Will,33,385)


#### Map Functions

In [10]:
lines.map((x:String) => x.split(",")).take(1)

res4: Array[Array[String]] = Array(Array(0, Will, 33, 385))


In [13]:
def parseLine(line: String)={
    val fields = line.split(",")
    val age = fields(2).toInt
    val numFriends = fields(3).toInt
    (age,numFriends)
}

val rdd = lines.map(parseLine)

parseLine: (line: String)(Int, Int)
rdd: org.apache.spark.rdd.RDD[(Int, Int)] = MapPartitionsRDD[4] at map at <console>:33


In [15]:
rdd.take(5)

res6: Array[(Int, Int)] = Array((33,385), (26,2), (55,221), (40,465), (68,21))


In [17]:
rdd.mapValues(x => x).collect()

res8: Array[(Int, Int)] = Array((33,385), (26,2), (55,221), (40,465), (68,21), (59,318), (37,220), (54,307), (38,380), (27,181), (53,191), (57,372), (54,253), (56,444), (43,49), (36,49), (22,323), (35,13), (45,455), (60,246), (67,220), (19,268), (30,72), (51,271), (25,1), (21,445), (22,100), (42,363), (49,476), (48,364), (50,175), (39,161), (26,281), (53,197), (43,249), (27,305), (32,81), (58,21), (64,65), (31,192), (52,413), (67,167), (54,75), (58,345), (35,244), (52,77), (25,96), (24,49), (20,1), (40,254), (51,283), (36,212), (19,269), (62,31), (19,5), (41,278), (44,194), (57,294), (59,158), (59,284), (20,100), (62,442), (69,9), (58,54), (31,15), (52,169), (21,477), (48,135), (33,74), (30,204), (52,393), (45,184), (22,179), (20,384), (65,208), (40,459), (62,201), (40,407), (61,337), (...

In [20]:
rdd.mapValues(x => (x,1)).collect()

res10: Array[(Int, (Int, Int))] = Array((33,(385,1)), (26,(2,1)), (55,(221,1)), (40,(465,1)), (68,(21,1)), (59,(318,1)), (37,(220,1)), (54,(307,1)), (38,(380,1)), (27,(181,1)), (53,(191,1)), (57,(372,1)), (54,(253,1)), (56,(444,1)), (43,(49,1)), (36,(49,1)), (22,(323,1)), (35,(13,1)), (45,(455,1)), (60,(246,1)), (67,(220,1)), (19,(268,1)), (30,(72,1)), (51,(271,1)), (25,(1,1)), (21,(445,1)), (22,(100,1)), (42,(363,1)), (49,(476,1)), (48,(364,1)), (50,(175,1)), (39,(161,1)), (26,(281,1)), (53,(197,1)), (43,(249,1)), (27,(305,1)), (32,(81,1)), (58,(21,1)), (64,(65,1)), (31,(192,1)), (52,(413,1)), (67,(167,1)), (54,(75,1)), (58,(345,1)), (35,(244,1)), (52,(77,1)), (25,(96,1)), (24,(49,1)), (20,(1,1)), (40,(254,1)), (51,(283,1)), (36,(212,1)), (19,(269,1)), (62,(31,1)), (19,(5,1)), (41,(278...

In [18]:
val totalsByAge = rdd.mapValues(x => (x,1)).reduceByKey((x,y) => (x._1+y._1,x._2+y._2))

totalsByAge: org.apache.spark.rdd.RDD[(Int, (Int, Int))] = ShuffledRDD[8] at reduceByKey at <console>:26


In [19]:
totalsByAge.collect()

res9: Array[(Int, (Int, Int))] = Array((34,(1473,6)), (52,(3747,11)), (56,(1840,6)), (66,(2488,9)), (22,(1445,7)), (28,(2091,10)), (54,(3615,13)), (46,(2908,13)), (48,(2814,10)), (30,(2594,11)), (50,(1273,5)), (32,(2287,11)), (36,(2466,10)), (24,(1169,5)), (62,(2870,13)), (64,(3376,12)), (42,(1821,6)), (40,(4264,17)), (18,(2747,8)), (20,(825,5)), (38,(2903,15)), (58,(1282,11)), (44,(3386,12)), (60,(1419,7)), (26,(4115,17)), (68,(2696,10)), (19,(2346,11)), (39,(1185,7)), (41,(2417,9)), (61,(2306,9)), (21,(2807,8)), (47,(2099,9)), (55,(3842,13)), (53,(1560,7)), (25,(2172,11)), (29,(2591,12)), (59,(1980,9)), (65,(1491,5)), (35,(1693,8)), (27,(1825,8)), (57,(3106,12)), (51,(2115,7)), (33,(3904,12)), (37,(2244,9)), (23,(2463,10)), (45,(4024,13)), (63,(1536,4)), (67,(3434,16)), (69,(2352,10))...

In [21]:
val averageByAge = totalsByAge.mapValues(x => x._1/x._2)

averageByAge: org.apache.spark.rdd.RDD[(Int, Int)] = MapPartitionsRDD[10] at mapValues at <console>:26


In [24]:
averageByAge.sortByKey().collect()

res13: Array[(Int, Int)] = Array((18,343), (19,213), (20,165), (21,350), (22,206), (23,246), (24,233), (25,197), (26,242), (27,228), (28,209), (29,215), (30,235), (31,267), (32,207), (33,325), (34,245), (35,211), (36,246), (37,249), (38,193), (39,169), (40,250), (41,268), (42,303), (43,230), (44,282), (45,309), (46,223), (47,233), (48,281), (49,184), (50,254), (51,302), (52,340), (53,222), (54,278), (55,295), (56,306), (57,258), (58,116), (59,220), (60,202), (61,256), (62,220), (63,384), (64,281), (65,298), (66,276), (67,214), (68,269), (69,235))


In [27]:
averageByAge.sortByKey().foreach(print)

(44,282)(18,343)(19,213)(20,165)(21,350)(45,309)(22,206)(23,246)(24,233)(25,197)(26,242)(27,228)(28,209)(29,215)(30,235)(31,267)(32,207)(33,325)(46,223)(34,245)(47,233)(35,211)(48,281)(36,246)(49,184)(50,254)(51,302)(52,340)(53,222)(54,278)(55,295)(56,306)(57,258)(58,116)(59,220)(60,202)(61,256)(62,220)(63,384)(64,281)(65,298)(66,276)(67,214)(68,269)(69,235)(37,249)(38,193)(39,169)(40,250)(41,268)(42,303)(43,230)

#### Filter Functions

##### Find the minimum Temperature

In [29]:
val lines = sc.textFile("C:/workspace/workplace/scala/SparkScala/1800.csv")

lines: org.apache.spark.rdd.RDD[String] = C:/workspace/workplace/scala/SparkScala/1800.csv MapPartitionsRDD[24] at textFile at <console>:25


In [30]:
lines.take(3)

res17: Array[String] = Array(ITE00100554,18000101,TMAX,-75,,,E,, ITE00100554,18000101,TMIN,-148,,,E,, GM000010962,18000101,PRCP,0,,,E,)


In [31]:
0.5 * 0.1f * (9.0f / 5.0f) + 32.0f

res18: Double = 32.08999999895692


In [32]:
0.5 * 0.1 * (9.0 / 5.0) + 32.0

res19: Double = 32.09


In [34]:
def parseLine(line:String)={
    val fields = line.split(",")
    val stationID = fields(0)
    val entryType  = fields(2)
    val temperature = fields(3).toFloat * 0.1f * (9.0f / 5.0f ) + 32.0f
    (stationID,entryType,temperature)
}

parseLine: (line: String)(String, String, Float)


In [35]:
val parsedLines = lines.map(parseLine)

parsedLines: org.apache.spark.rdd.RDD[(String, String, Float)] = MapPartitionsRDD[25] at map at <console>:28


In [36]:
parsedLines.take(2)

res20: Array[(String, String, Float)] = Array((ITE00100554,TMAX,18.5), (ITE00100554,TMIN,5.3600006))


In [37]:
val minTemps = parsedLines.filter(x => x._2 == "TMIN")

minTemps: org.apache.spark.rdd.RDD[(String, String, Float)] = MapPartitionsRDD[26] at filter at <console>:26


In [38]:
minTemps.take(2)

res21: Array[(String, String, Float)] = Array((ITE00100554,TMIN,5.3600006), (EZE00100082,TMIN,7.700001))


In [39]:
val stationTemps = minTemps.map(x => (x._1,x._3.toFloat))

stationTemps: org.apache.spark.rdd.RDD[(String, Float)] = MapPartitionsRDD[27] at map at <console>:26


In [41]:
stationTemps.take(2)

res23: Array[(String, Float)] = Array((ITE00100554,5.3600006), (EZE00100082,7.700001))


In [43]:
import scala.math.min
val minTempsByStation = stationTemps.reduceByKey( (x,y) => min(x,y))

import scala.math.min
minTempsByStation: org.apache.spark.rdd.RDD[(String, Float)] = ShuffledRDD[28] at reduceByKey at <console>:27


In [44]:
minTempsByStation.collect()

res24: Array[(String, Float)] = Array((EZE00100082,7.700001), (ITE00100554,5.3600006))


In [45]:
stationTemps.collect()

res25: Array[(String, Float)] = Array((ITE00100554,5.3600006), (EZE00100082,7.700001), (ITE00100554,9.5), (EZE00100082,8.6), (ITE00100554,23.720001), (EZE00100082,18.86), (ITE00100554,29.66), (EZE00100082,18.68), (ITE00100554,30.92), (EZE00100082,21.56), (ITE00100554,34.34), (EZE00100082,21.74), (ITE00100554,33.8), (EZE00100082,23.0), (ITE00100554,34.52), (EZE00100082,26.42), (ITE00100554,36.14), (EZE00100082,23.720001), (ITE00100554,37.58), (EZE00100082,18.5), (ITE00100554,39.38), (EZE00100082,20.84), (ITE00100554,37.22), (EZE00100082,21.2), (ITE00100554,34.34), (EZE00100082,21.2), (ITE00100554,36.14), (EZE00100082,25.7), (ITE00100554,39.38), (EZE00100082,27.86), (ITE00100554,39.38), (EZE00100082,25.34), (ITE00100554,40.64), (EZE00100082,25.7), (ITE00100554,40.28), (EZE00100082,33.62),...

In [49]:
minTempsByStation.collect().foreach((x) => println(x._1+" --> "+x._2))

EZE00100082 --> 7.700001
ITE00100554 --> 5.3600006


##### Find the Maximum Temperature

In [51]:
import scala.math.max

val maxTemps = parsedLines.filter(x => x._2 == "TMAX")
val stationTemps = maxTemps.map(x => (x._1,x._3.toFloat))
val maxTempsByStation = stationTemps.reduceByKey( (x,y) => max(x,y))
maxTempsByStation.collect().foreach((x) => println(x._1+" --> "+x._2))

EZE00100082 --> 90.14
ITE00100554 --> 90.14


import scala.math.max
maxTemps: org.apache.spark.rdd.RDD[(String, String, Float)] = MapPartitionsRDD[29] at filter at <console>:31
stationTemps: org.apache.spark.rdd.RDD[(String, Float)] = MapPartitionsRDD[30] at map at <console>:32
maxTempsByStation: org.apache.spark.rdd.RDD[(String, Float)] = ShuffledRDD[31] at reduceByKey at <console>:33


###### FlatMap vs Map

In [53]:
val lines = sc.textFile("C:/workspace/workplace/scala/SparkScala/book.txt")

lines: org.apache.spark.rdd.RDD[String] = C:/workspace/workplace/scala/SparkScala/book.txt MapPartitionsRDD[33] at textFile at <console>:27


In [58]:
lines.take(4).foreach(println)

Self-Employment: Building an Internet Business of One
Achieving Financial and Personal Freedom through a Lifestyle Technology Business
By Frank Kane



In [60]:
val mapLine = lines.map(x => x.split(" "))

mapLine: org.apache.spark.rdd.RDD[Array[String]] = MapPartitionsRDD[35] at map at <console>:28


In [65]:
mapLine.take(4)

res42: Array[Array[String]] = Array(Array(Self-Employment:, Building, an, Internet, Business, of, One), Array(Achieving, Financial, and, Personal, Freedom, through, a, Lifestyle, Technology, Business), Array(By, Frank, Kane), Array(""))


In [66]:
mapLine.take(4)(0)

res43: Array[String] = Array(Self-Employment:, Building, an, Internet, Business, of, One)


In [68]:
mapLine.take(4)(0).length

res45: Int = 7


In [69]:
val flatmapLine = lines.flatMap(x => x.split(" "))

flatmapLine: org.apache.spark.rdd.RDD[String] = MapPartitionsRDD[36] at flatMap at <console>:28


In [70]:
flatmapLine.take(4)

res46: Array[String] = Array(Self-Employment:, Building, an, Internet)


In [71]:
flatmapLine.collect()

res47: Array[String] = Array(Self-Employment:, Building, an, Internet, Business, of, One, Achieving, Financial, and, Personal, Freedom, through, a, Lifestyle, Technology, Business, By, Frank, Kane, "", "", "", Copyright, ?, 2015, Frank, Kane., All, rights, reserved, worldwide., "", "", CONTENTS, Disclaimer, Preface, Part, I:, Making, the, Big, Decision, Overcoming, Inertia, Fear, of, Failure, Career, Indoctrination, The, Carrot, on, a, Stick, Ego, Protection, Your, Employer, as, a, Security, Blanket, Why, it?s, Worth, it, Unlimited, Growth, Potential, Investing, in, Yourself,, Not, Someone, Else, No, Dependencies, No, Commute, Freedom, to, Live, Where, You, Want, Freedom, to, Work, When, You, Want, Freedom, to, Work, How, You, Want, Is, Self-Employment, for, You?, Flowchart:, Should, I,...

In [72]:
flatmapLine.countByValue()

res48: scala.collection.Map[String,Long] = Map(foolproof -> 1, precious -> 1, inflammatory -> 1, referrer, -> 1, hourly -> 3, embedded -> 1, way). -> 1, touch, -> 1, of. -> 3, salesperson -> 5, Leeches -> 1, expansion. -> 1, rate -> 7, appropriate. -> 2, CPA?s -> 1, 2014 -> 2, WELL-MEANING -> 1, Talk -> 5, Much -> 1, Builder" -> 1, plugin -> 3, headache -> 1, purchasing -> 9, China" -> 1, looks -> 2, site, -> 7, ranking -> 2, scare -> 1, hard-earned -> 1, freedom? -> 1, Seattle, -> 3, PULLING -> 1, action. -> 1, accident -> 3, scale. -> 2, looking. -> 1, physically -> 1, 27, -> 1, call. -> 1, contracts -> 3, twofold. -> 1, scenario -> 1, Advertising -> 3, way? -> 2, nudge -> 1, gamble -> 1, ideas -> 19, sketches -> 1, static -> 1, freelancer. -> 1, ?PR:? -> 1, joining -> 1, particularly...

In [77]:
flatmapLine.countByValue().take(3)

res53: scala.collection.Map[String,Long] = Map(foolproof -> 1, precious -> 1, inflammatory -> 1)


In [82]:
lines.flatMap(x => x.split("\\W+")).map(x=> x.toLowerCase())

res58: org.apache.spark.rdd.RDD[String] = MapPartitionsRDD[52] at map at <console>:30


In [83]:
lines.flatMap(x => x.split("\\W+")).map(x=> x.toLowerCase()).countByValue()

res59: scala.collection.Map[String,Long] = Map(serious -> 1, foolproof -> 1, precious -> 2, inflammatory -> 1, hourly -> 3, embedded -> 1, salesperson -> 7, plentiful -> 1, rate -> 9, 2014 -> 8, plugin -> 3, headache -> 1, purchasing -> 9, ons -> 1, bing -> 1, looks -> 2, ranking -> 2, irs -> 3, california -> 2, scare -> 1, finalized -> 1, associations -> 1, accident -> 3, physically -> 2, conversations -> 1, contracts -> 4, scenario -> 1, nudge -> 2, gamble -> 4, ideas -> 27, sketches -> 1, static -> 1, oculus -> 5, unity -> 1, tweeted -> 1, joining -> 1, particularly -> 1, used -> 18, eye -> 3, striking -> 2, minority -> 1, automatic -> 2, widely -> 4, impressions -> 5, checklist -> 3, e -> 1, conversion -> 4, worded -> 1, unidirectional -> 1, significantly -> 4, beautiful -> 1, provi...

In [85]:
lines.flatMap(x => x.split("\\W+")).map(x=> x.toLowerCase()).countByValue()

res61: scala.collection.Map[String,Long] = Map(serious -> 1, foolproof -> 1, precious -> 2, inflammatory -> 1, hourly -> 3, embedded -> 1, salesperson -> 7, plentiful -> 1, rate -> 9, 2014 -> 8, plugin -> 3, headache -> 1, purchasing -> 9, ons -> 1, bing -> 1, looks -> 2, ranking -> 2, irs -> 3, california -> 2, scare -> 1, finalized -> 1, associations -> 1, accident -> 3, physically -> 2, conversations -> 1, contracts -> 4, scenario -> 1, nudge -> 2, gamble -> 4, ideas -> 27, sketches -> 1, static -> 1, oculus -> 5, unity -> 1, tweeted -> 1, joining -> 1, particularly -> 1, used -> 18, eye -> 3, striking -> 2, minority -> 1, automatic -> 2, widely -> 4, impressions -> 5, checklist -> 3, e -> 1, conversion -> 4, worded -> 1, unidirectional -> 1, significantly -> 4, beautiful -> 1, provi...

In [91]:
val wordCounts = lines.flatMap(x => x.split("\\W+")).map(x=> (x,1)).reduceByKey( (x,y) => x + y)

wordCounts: org.apache.spark.rdd.RDD[(String, Int)] = ShuffledRDD[75] at reduceByKey at <console>:28


In [93]:
val sortedWcounts = wordCounts.map(x => (x._2,x._1)).sortByKey()

sortedWcounts: org.apache.spark.rdd.RDD[(Int, String)] = ShuffledRDD[83] at sortByKey at <console>:28


In [94]:
sortedWcounts.take(2)

res66: Array[(Int, String)] = Array((1,transitions), (1,intimately))


In [98]:
// for (result <- sortedWcounts) {
//       val count = result._1
//       val word = result._2
//       println(s"$word: $count")
//     }
sortedWcounts.take(5)

res70: Array[(Int, String)] = Array((1,transitions), (1,intimately), (1,SEARCH), (1,312), (1,conjure))


### Advanced

In [102]:
import scala.io.Source
val lines = Source.fromFile("C:/workspace/workplace/scala/SparkScala/ml-100k/u.item").getLines()

import scala.io.Source
lines: Iterator[String] = non-empty iterator


In [107]:
lines.next

res74: String = 1|Toy Story (1995)|01-Jan-1995||http://us.imdb.com/M/title-exact?Toy%20Story%20(1995)|0|0|0|1|1|1|0|0|0|0|0|0|0|0|0|0|0|0|0


In [108]:
lines.next

res75: String = 2|GoldenEye (1995)|01-Jan-1995||http://us.imdb.com/M/title-exact?GoldenEye%20(1995)|0|1|1|0|0|0|0|0|0|0|0|0|0|0|0|0|1|0|0


In [109]:
lines.length

res76: Int = 1680


In [119]:
val lines = Source.fromFile("C:/workspace/workplace/scala/SparkScala/ml-100k/u.item").getLines()

lines: Iterator[String] = non-empty iterator


In [120]:
var movieNames : Map[Int,String]=Map()
for(line <- lines){
    var fields = line.split("|")
    if(fields.length > 1){
        movieNames += (fields(0).toInt -> fields(1) )
}
}

movieNames: Map[Int,String] = Map(5 -> 9, 1 -> 6, 6 -> 9, 9 -> 9, 2 -> 9, 7 -> 9, 3 -> 9, 8 -> 9, 4 -> 9)


In [1]:
import scala.io.Source
import java.nio.charset.CodingErrorAction
import scala.io.Codec
def loadMoviesName(): Map[Int,String] = {
    // Handle character encoding issues:
    implicit val codec = Codec("UTF-8")
    codec.onMalformedInput(CodingErrorAction.REPLACE)
    codec.onUnmappableCharacter(CodingErrorAction.REPLACE)
    
    val lines = Source.fromFile("C:/workspace/workplace/scala/SparkScala/ml-100k/u.item").getLines()
    var movieNames : Map[Int,String]=Map()
    for(line <- lines){
        var fields = line.split('|')
        if(fields.length > 1){
            movieNames += (fields(0).toInt -> fields(1))
        }
        
    }
    return movieNames
}

Intitializing Scala interpreter ...

Spark Web UI available at http://DESKTOP-7M17AKF:4040
SparkContext available as 'sc' (version = 2.4.5, master = local[*], app id = local-1589277575557)
SparkSession available as 'spark'


import scala.io.Source
import java.nio.charset.CodingErrorAction
import scala.io.Codec
loadMoviesName: ()Map[Int,String]


In [2]:
val n = loadMoviesName()

n: Map[Int,String] = Map(645 -> Paris Is Burning (1990), 892 -> Flubber (1997), 69 -> Forrest Gump (1994), 1322 -> Metisse (Caf? au Lait) (1993), 1665 -> Brother's Kiss, A (1997), 1036 -> Drop Dead Fred (1991), 1586 -> Lashou shentan (1992), 1501 -> Prisoner of the Mountains (Kavkazsky Plennik) (1996), 809 -> Rising Sun (1993), 1337 -> Larger Than Life (1996), 1411 -> Barbarella (1968), 629 -> Victor/Victoria (1982), 1024 -> Mrs. Dalloway (1997), 1469 -> Tom and Huck (1995), 365 -> Powder (1995), 1369 -> Forbidden Christ, The (Cristo proibito, Il) (1950), 138 -> D3: The Mighty Ducks (1996), 1190 -> That Old Feeling (1997), 1168 -> Little Buddha (1993), 760 -> Screamers (1995), 101 -> Heavy Metal (1981), 1454 -> Angel and the Badman (1947), 1633 -> ? k?ldum klaka (Cold Fever) (1994), 479...

In [3]:
var nameDict = sc.broadcast(loadMoviesName) 

nameDict: org.apache.spark.broadcast.Broadcast[Map[Int,String]] = Broadcast(0)


In [5]:
val lines = sc.textFile("C:/workspace/workplace/scala/SparkScala/ml-100k/u.data")

lines: org.apache.spark.rdd.RDD[String] = C:/workspace/workplace/scala/SparkScala/ml-100k/u.data MapPartitionsRDD[1] at textFile at <console>:26


In [6]:
val movies = lines.map(x => (x.split("\t")(1).toInt,1))

movies: org.apache.spark.rdd.RDD[(Int, Int)] = MapPartitionsRDD[2] at map at <console>:27


In [7]:
movies.take(1)

res0: Array[(Int, Int)] = Array((242,1))


In [8]:
val moviesCounts = movies.reduceByKey((x,y) => x+y)

moviesCounts: org.apache.spark.rdd.RDD[(Int, Int)] = ShuffledRDD[3] at reduceByKey at <console>:27


In [9]:
moviesCounts.take(2)

res1: Array[(Int, Int)] = Array((454,16), (1084,21))


In [10]:
val flipped = moviesCounts.map(x => (x._2,x._1))

flipped: org.apache.spark.rdd.RDD[(Int, Int)] = MapPartitionsRDD[4] at map at <console>:27


In [14]:
flipped.take(2)

res3: Array[(Int, Int)] = Array((16,454), (21,1084))


In [16]:
val moviesSorted = flipped.sortByKey()

moviesSorted: org.apache.spark.rdd.RDD[(Int, Int)] = ShuffledRDD[8] at sortByKey at <console>:27


In [17]:
moviesSorted.take(2)

res4: Array[(Int, Int)] = Array((1,1494), (1,1414))


#### DataFrame

In [1]:
import org.apache.spark.sql._
import org.apache.spark.SparkContext._
import org.apache.spark._

import org.apache.spark.sql._
import org.apache.spark.SparkContext._
import org.apache.spark._


In [41]:
case class Person(ID:Int, name:String, age:Int, numFriends:Int)

defined class Person


In [47]:
def mapper(line:String): Person = {
    val fields = line.split(',')
    val person:Person = Person(fields(0).toInt,fields(1),fields(2).toInt,fields(3).toInt)
    return person
}

mapper: (line: String)Person


In [5]:
val spark = SparkSession.builder.appName("SparkSQL").master("local[*]").config("spark.sql.warehouse.dir","file:///C:/workspace/spark/hive").getOrCreate()

spark: org.apache.spark.sql.SparkSession = org.apache.spark.sql.SparkSession@2a0a1b43


In [6]:
import spark.implicits._

import spark.implicits._


In [43]:
val lines = spark.sparkContext.textFile("C:/workspace/workplace/scala/SparkScala/fakefriends.csv")

lines: org.apache.spark.rdd.RDD[String] = C:/workspace/workplace/scala/SparkScala/fakefriends.csv MapPartitionsRDD[76] at textFile at <console>:38


In [48]:
val people = lines.map(mapper).toDS().cache()

people: org.apache.spark.sql.Dataset[Person] = [ID: int, name: string ... 2 more fields]


In [49]:
 println("Here is our inferred schema:")
people.printSchema()

Here is our inferred schema:
root
 |-- ID: integer (nullable = false)
 |-- name: string (nullable = true)
 |-- age: integer (nullable = false)
 |-- numFriends: integer (nullable = false)



In [54]:
lines.take(2)

res26: Array[String] = Array(0,Will,33,385, 1,Jean-Luc,26,2)


In [55]:
lines.map(x => x.split(','))

res27: org.apache.spark.rdd.RDD[Array[String]] = MapPartitionsRDD[96] at map at <console>:42


In [60]:
val people = spark.read.csv("C:/workspace/workplace/scala/SparkScala/fakefriends.csv")

people: org.apache.spark.sql.DataFrame = [_c0: string, _c1: string ... 2 more fields]


In [61]:
people.show(3)

+---+--------+---+---+
|_c0|     _c1|_c2|_c3|
+---+--------+---+---+
|  0|    Will| 33|385|
|  1|Jean-Luc| 26|  2|
|  2|    Hugh| 55|221|
+---+--------+---+---+
only showing top 3 rows



In [69]:
people.groupBy("_c1").sum().collect()

res40: Array[org.apache.spark.sql.Row] = Array([Data], [Beverly], [Hugh], [Dukat], [Jean-Luc], [Nog], [Odo], [Kasidy], [Guinan], [Leeta], [Rom], [Geordi], [Brunt], [Deanna], [Ben], [Weyoun], [Miles], [Will], [Julian], [Lwaxana], [Jadzia], [Ezri], [Keiko], [Elim], [Worf], [Nerys], [Quark], [Martok], [Morn], [Gowron])


##### working with class

In [1]:
case class Person(ID:Int, name:String, age:Int, numFriends:Int)

Intitializing Scala interpreter ...

Spark Web UI available at http://DESKTOP-7M17AKF:4040
SparkContext available as 'sc' (version = 2.4.5, master = local[*], app id = local-1589341912310)
SparkSession available as 'spark'


defined class Person


In [3]:
val person: Person = Person(1,"will",33,342)

person: Person = Person(1,will,33,342)


In [4]:
person

res0: Person = Person(1,will,33,342)


In [30]:
def mapper(line:String): Person={
    val fields = line.split(',')
    val person: Person = Person(fields(0).toInt, fields(1),fields(2).toInt,fields(3).toInt)
    return person
}

mapper: (line: String)Person


In [7]:
import org.apache.spark.sql._
import org.apache.spark.SparkContext._
import org.apache.spark._
val spark = SparkSession.builder.appName("SparkSQL").master("local[*]").config("spark.sql.warehouse.dir","file:///C:/workspace/spark/hive").getOrCreate()

import org.apache.spark.sql._
import org.apache.spark.SparkContext._
import org.apache.spark._
spark: org.apache.spark.sql.SparkSession = org.apache.spark.sql.SparkSession@5c324076


In [10]:
import spark.implicits._
val lines = spark.sparkContext.textFile("C:/workspace/workplace/scala/SparkScala/fakefriends.csv")

import spark.implicits._
lines: org.apache.spark.rdd.RDD[String] = C:/workspace/workplace/scala/SparkScala/fakefriends.csv MapPartitionsRDD[21] at textFile at <console>:42


In [43]:
import org.apache.spark.sql.types._

val customSchema = StructType(Array(
  StructField("ID", IntegerType, true),
  StructField("name", StringType, true),
  StructField("age", IntegerType, true),
  StructField("numFriends", IntegerType, true)
))

val csv_df = spark.read.format("csv").schema(customSchema).load("C:/workspace/workplace/scala/SparkScala/fakefriends.csv")


import org.apache.spark.sql.types._
customSchema: org.apache.spark.sql.types.StructType = StructType(StructField(ID,IntegerType,true), StructField(name,StringType,true), StructField(age,IntegerType,true), StructField(numFriends,IntegerType,true))
csv_df: org.apache.spark.sql.DataFrame = [ID: int, name: string ... 2 more fields]


In [44]:
csv_df.show()

+---+--------+---+----------+
| ID|    name|age|numFriends|
+---+--------+---+----------+
|  0|    Will| 33|       385|
|  1|Jean-Luc| 26|         2|
|  2|    Hugh| 55|       221|
|  3|  Deanna| 40|       465|
|  4|   Quark| 68|        21|
|  5|  Weyoun| 59|       318|
|  6|  Gowron| 37|       220|
|  7|    Will| 54|       307|
|  8|  Jadzia| 38|       380|
|  9|    Hugh| 27|       181|
| 10|     Odo| 53|       191|
| 11|     Ben| 57|       372|
| 12|   Keiko| 54|       253|
| 13|Jean-Luc| 56|       444|
| 14|    Hugh| 43|        49|
| 15|     Rom| 36|        49|
| 16|  Weyoun| 22|       323|
| 17|     Odo| 35|        13|
| 18|Jean-Luc| 45|       455|
| 19|  Geordi| 60|       246|
+---+--------+---+----------+
only showing top 20 rows



In [51]:
csv_df.rdd.collect()(1)

res35: org.apache.spark.sql.Row = [1,Jean-Luc,26,2]


In [52]:
csv_df.createOrReplaceTempView("people")

In [56]:
spark.sql("SELECT * FROM people where numFriends > 300").count()

res40: Long = 198


In [59]:
spark.sql("SELECT name,age,age+10 FROM people").show()

+--------+---+----------+
|    name|age|(age + 10)|
+--------+---+----------+
|    Will| 33|        43|
|Jean-Luc| 26|        36|
|    Hugh| 55|        65|
|  Deanna| 40|        50|
|   Quark| 68|        78|
|  Weyoun| 59|        69|
|  Gowron| 37|        47|
|    Will| 54|        64|
|  Jadzia| 38|        48|
|    Hugh| 27|        37|
|     Odo| 53|        63|
|     Ben| 57|        67|
|   Keiko| 54|        64|
|Jean-Luc| 56|        66|
|    Hugh| 43|        53|
|     Rom| 36|        46|
|  Weyoun| 22|        32|
|     Odo| 35|        45|
|Jean-Luc| 45|        55|
|  Geordi| 60|        70|
+--------+---+----------+
only showing top 20 rows



In [66]:
csv_df.select($"name",$"age").filter($"age" > 30).show()

+--------+---+
|    name|age|
+--------+---+
|    Will| 33|
|    Hugh| 55|
|  Deanna| 40|
|   Quark| 68|
|  Weyoun| 59|
|  Gowron| 37|
|    Will| 54|
|  Jadzia| 38|
|     Odo| 53|
|     Ben| 57|
|   Keiko| 54|
|Jean-Luc| 56|
|    Hugh| 43|
|     Rom| 36|
|     Odo| 35|
|Jean-Luc| 45|
|  Geordi| 60|
|     Odo| 67|
|   Keiko| 51|
|   Leeta| 42|
+--------+---+
only showing top 20 rows



In [67]:
csv_df.filter($"age" > 30).select($"name",$"age").show()

+--------+---+
|    name|age|
+--------+---+
|    Will| 33|
|    Hugh| 55|
|  Deanna| 40|
|   Quark| 68|
|  Weyoun| 59|
|  Gowron| 37|
|    Will| 54|
|  Jadzia| 38|
|     Odo| 53|
|     Ben| 57|
|   Keiko| 54|
|Jean-Luc| 56|
|    Hugh| 43|
|     Rom| 36|
|     Odo| 35|
|Jean-Luc| 45|
|  Geordi| 60|
|     Odo| 67|
|   Keiko| 51|
|   Leeta| 42|
+--------+---+
only showing top 20 rows



In [69]:
csv_df.show(3)

+---+--------+---+----------+
| ID|    name|age|numFriends|
+---+--------+---+----------+
|  0|    Will| 33|       385|
|  1|Jean-Luc| 26|         2|
|  2|    Hugh| 55|       221|
+---+--------+---+----------+
only showing top 3 rows



##### New RDDs

In [2]:
val rdd = sc.textFile("C:/workspace/workplace/scala/SparkScala/fakefriends.csv")

rdd: org.apache.spark.rdd.RDD[String] = C:/workspace/workplace/scala/SparkScala/fakefriends.csv MapPartitionsRDD[1] at textFile at <console>:31


In [74]:
rdd.take(2)

res54: Array[String] = Array(0,Will,33,385, 1,Jean-Luc,26,2)


In [79]:
rdd.collect()

res58: Array[String] = Array(0,Will,33,385, 1,Jean-Luc,26,2, 2,Hugh,55,221, 3,Deanna,40,465, 4,Quark,68,21, 5,Weyoun,59,318, 6,Gowron,37,220, 7,Will,54,307, 8,Jadzia,38,380, 9,Hugh,27,181, 10,Odo,53,191, 11,Ben,57,372, 12,Keiko,54,253, 13,Jean-Luc,56,444, 14,Hugh,43,49, 15,Rom,36,49, 16,Weyoun,22,323, 17,Odo,35,13, 18,Jean-Luc,45,455, 19,Geordi,60,246, 20,Odo,67,220, 21,Miles,19,268, 22,Quark,30,72, 23,Keiko,51,271, 24,Julian,25,1, 25,Ben,21,445, 26,Julian,22,100, 27,Leeta,42,363, 28,Martok,49,476, 29,Nog,48,364, 30,Keiko,50,175, 31,Miles,39,161, 32,Nog,26,281, 33,Dukat,53,197, 34,Jean-Luc,43,249, 35,Beverly,27,305, 36,Kasidy,32,81, 37,Geordi,58,21, 38,Deanna,64,65, 39,Morn,31,192, 40,Odo,52,413, 41,Hugh,67,167, 42,Brunt,54,75, 43,Guinan,58,345, 44,Nerys,35,244, 45,Dukat,52,77, 46,Morn,...

In [84]:
//rdd.map(x => x.split(",")).collect() ----- aome ide issue

```
scala> val rdd = sc.textFile("C:/workspace/workplace/scala/SparkScala/fakefriends.csv")
rdd: org.apache.spark.rdd.RDD[String] = C:/workspace/workplace/scala/SparkScala/fakefriends.csv MapPartitionsRDD[1] at textFile at <console>:24

scala> rdd.map(x => x.split(",")).collect()
res0: Array[Array[String]] = Array(Array(0, Will, 33, 385), Array(1, Jean-Luc, 26, 2), Array(2, Hugh, 55, 221), Array(3, Deanna, 40, 465), Array(4, Quark, 68, 21), Array(5, Weyoun, 59, 318), Array(6, Gowron, 37, 220), Array(7, Will, 54, 307), Array(8, Jadzia, 38, 380), Array(9, Hugh, 27, 181), Array(10, Odo, 53, 191), Array(11, Ben, 57, 372), Array(12, Keiko, 54, 253), Array(13, Jean-Luc, 56, 444), Array(14, Hugh, 43, 49), Array(15, Rom, 36, 49), Array(16, Weyoun, 22, 323), Array(17, Odo, 35, 13), Array(18, Jean-Luc, 45, 455), Array(19, Geordi, 60, 246), Array(20, Odo, 67, 220), Array(21, Miles, 19, 268), Array(22, Quark, 30, 72), Array(23, Keiko, 51, 271), Array(24, Julian, 25, 1), Array(25, Ben, 21, 445), Array(26, Julian, 22, 100), Array(27, Leeta, 42, 363), Array(28, Martok, 49, 476...
scala>

scala> case class Person(ID:Int,name:String, age:Int, numFriends:Int)
defined class Person

scala> rdd.map(x => x.split(",")).map(x => Person(x(0).toInt, x(1),x(2).toInt, x(3).toInt) )
res1: org.apache.spark.rdd.RDD[Person] = MapPartitionsRDD[4] at map at <console>:28

scala> val rdd2df = rdd.map(x => x.split(",")).map(x => Person(x(0).toInt, x(1),x(2).toInt, x(3).toInt))
rdd2df: org.apache.spark.rdd.RDD[Person] = MapPartitionsRDD[6] at map at <console>:27

scala> rdd2df.take(3)
res2: Array[Person] = Array(Person(0,Will,33,385), Person(1,Jean-Luc,26,2), Person(2,Hugh,55,221))

scala> rdd2df.toDS()
res3: org.apache.spark.sql.Dataset[Person] = [ID: int, name: string ... 2 more fields]

scala> rdd2df.toDS().take(2)
res4: Array[Person] = Array(Person(0,Will,33,385), Person(1,Jean-Luc,26,2))

scala> val data = rdd2df.toDS().cache()
data: org.apache.spark.sql.Dataset[Person] = [ID: int, name: string ... 2 more fields]


scala> data.show(1)
+---+----+---+----------+
| ID|name|age|numFriends|
+---+----+---+----------+
|  0|Will| 33|       385|
+---+----+---+----------+
only showing top 1 row
```

In [85]:
csv_df.show()

+---+--------+---+----------+
| ID|    name|age|numFriends|
+---+--------+---+----------+
|  0|    Will| 33|       385|
|  1|Jean-Luc| 26|         2|
|  2|    Hugh| 55|       221|
|  3|  Deanna| 40|       465|
|  4|   Quark| 68|        21|
|  5|  Weyoun| 59|       318|
|  6|  Gowron| 37|       220|
|  7|    Will| 54|       307|
|  8|  Jadzia| 38|       380|
|  9|    Hugh| 27|       181|
| 10|     Odo| 53|       191|
| 11|     Ben| 57|       372|
| 12|   Keiko| 54|       253|
| 13|Jean-Luc| 56|       444|
| 14|    Hugh| 43|        49|
| 15|     Rom| 36|        49|
| 16|  Weyoun| 22|       323|
| 17|     Odo| 35|        13|
| 18|Jean-Luc| 45|       455|
| 19|  Geordi| 60|       246|
+---+--------+---+----------+
only showing top 20 rows



`=====================================================`

In [8]:
rdd.map(x => x.split(",")).collect()

res5: Array[Array[String]] = Array(Array(0, Will, 33, 385), Array(1, Jean-Luc, 26, 2), Array(2, Hugh, 55, 221), Array(3, Deanna, 40, 465), Array(4, Quark, 68, 21), Array(5, Weyoun, 59, 318), Array(6, Gowron, 37, 220), Array(7, Will, 54, 307), Array(8, Jadzia, 38, 380), Array(9, Hugh, 27, 181), Array(10, Odo, 53, 191), Array(11, Ben, 57, 372), Array(12, Keiko, 54, 253), Array(13, Jean-Luc, 56, 444), Array(14, Hugh, 43, 49), Array(15, Rom, 36, 49), Array(16, Weyoun, 22, 323), Array(17, Odo, 35, 13), Array(18, Jean-Luc, 45, 455), Array(19, Geordi, 60, 246), Array(20, Odo, 67, 220), Array(21, Miles, 19, 268), Array(22, Quark, 30, 72), Array(23, Keiko, 51, 271), Array(24, Julian, 25, 1), Array(25, Ben, 21, 445), Array(26, Julian, 22, 100), Array(27, Leeta, 42, 363), Array(28, Martok, 49, 476...

In [9]:
val BroadCast = sc.broadcast(rdd.map(x => x.split(",")).collect())

BroadCast: org.apache.spark.broadcast.Broadcast[Array[Array[String]]] = Broadcast(4)


In [12]:
BroadCast.value

res7: Array[Array[String]] = Array(Array(0, Will, 33, 385), Array(1, Jean-Luc, 26, 2), Array(2, Hugh, 55, 221), Array(3, Deanna, 40, 465), Array(4, Quark, 68, 21), Array(5, Weyoun, 59, 318), Array(6, Gowron, 37, 220), Array(7, Will, 54, 307), Array(8, Jadzia, 38, 380), Array(9, Hugh, 27, 181), Array(10, Odo, 53, 191), Array(11, Ben, 57, 372), Array(12, Keiko, 54, 253), Array(13, Jean-Luc, 56, 444), Array(14, Hugh, 43, 49), Array(15, Rom, 36, 49), Array(16, Weyoun, 22, 323), Array(17, Odo, 35, 13), Array(18, Jean-Luc, 45, 455), Array(19, Geordi, 60, 246), Array(20, Odo, 67, 220), Array(21, Miles, 19, 268), Array(22, Quark, 30, 72), Array(23, Keiko, 51, 271), Array(24, Julian, 25, 1), Array(25, Ben, 21, 445), Array(26, Julian, 22, 100), Array(27, Leeta, 42, 363), Array(28, Martok, 49, 476...

In [1]:
import org.apache.spark.SparkContext._
import org.apache.spark.sql._

Intitializing Scala interpreter ...

Spark Web UI available at http://DESKTOP-7M17AKF:4041
SparkContext available as 'sc' (version = 2.4.5, master = local[*], app id = local-1589359729637)
SparkSession available as 'spark'


import org.apache.spark.SparkContext._
import org.apache.spark.sql._


In [9]:
val fakefriendsdf=rdd.map(x=> x.split(",")).toDF()

fakefriendsdf: org.apache.spark.sql.DataFrame = [value: array<string>]


In [10]:
fakefriendsdf.head()

res1: org.apache.spark.sql.Row = [WrappedArray(0, Will, 33, 385)]


In [11]:
rdd.map(x=> x.split(",")).toDS().show()

+--------------------+
|               value|
+--------------------+
|  [0, Will, 33, 385]|
|[1, Jean-Luc, 26, 2]|
|  [2, Hugh, 55, 221]|
|[3, Deanna, 40, 465]|
|  [4, Quark, 68, 21]|
|[5, Weyoun, 59, 318]|
|[6, Gowron, 37, 220]|
|  [7, Will, 54, 307]|
|[8, Jadzia, 38, 380]|
|  [9, Hugh, 27, 181]|
|  [10, Odo, 53, 191]|
|  [11, Ben, 57, 372]|
|[12, Keiko, 54, 253]|
|[13, Jean-Luc, 56...|
|  [14, Hugh, 43, 49]|
|   [15, Rom, 36, 49]|
|[16, Weyoun, 22, ...|
|   [17, Odo, 35, 13]|
|[18, Jean-Luc, 45...|
|[19, Geordi, 60, ...|
+--------------------+
only showing top 20 rows

